TARGET = sync_kasi_sdo

CC = gcc
LD = gcc 

CFLAGS = -I./curl/curl-7.45.0/include
LFLAGS = ./curl/curl-7.45.0/lib/.libs/libcurl.a -lcrypto -lssl -lldap -lidn

DEPS = dirs.h list.h sdo_data.h kasi_server.h log.h
OBJ = main.o dirs.o log.o work.o

%.o: %.c $(DEPS)
	$(CC) -c -o $@ $< $(CFLAGS)

$(TARGET) : $(OBJ)
	$(LD) -o $@ $^ $(LFLAGS)
	mv $@ ../


clean:
	rm -f $(TARGET) $(OBJ)
